//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public int IDestado { get; set; }
        public int IDpais { get; set; }
        public string Estado { get; set; }
        public string Sigla { get; set; }
    }
}
