//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IDusuario { get; set; }
        public string Nome { get; set; }
        public string Loginn { get; set; }
        public string Senha { get; set; }
        public string Email { get; set; }
    }
}
